[cite_start]name: Analisis de Action Checkout  # 

[cite_start]on: [push]  # Evento que dispara la action 

[cite_start]jobs:  # 
  build:
    [cite_start]runs-on: ubuntu-latest  # Entorno de ejecuci√≥n 

    [cite_start]steps:  # Pasos a seguir 
      - name: Checkout del codigo
        [cite_start]uses: actions/checkout@v4  # Uso de 'uses' 

      - name: Verificar archivos
        [cite_start]run: ls -R  # Uso de 'run' 
